;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        company-quickhelp-manual-begin
        dabbrev-expand
        electric-newline-and-maybe-indent
        end-of-buffer
        eval-and-replace
        indent-for-tab-command
        kill-region
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        paredit-open-round
        paredit-semicolon
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        electric-pair-delete-pair
        helm-M-x
        ido-find-file
        markdown-exdent-or-delete
        mouse-set-region
        previous-buffer
        reindent-then-newline-and-indent
        smex
        ))
