;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        indent-for-tab-command
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        paredit-semicolon
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        smex
        ))
